### ISSUE TITLE
T018: editor workflow using the FLAT FOLIA editor as an example

### ISSUE THREAD

**Issue by menzowindhouwer** [meertensinstituut/clariah-wp3-vre#4]
1. an editor recipe returns 
```xml
<iframe src="url to the editor with the resource loaded"/>
```

2. an editor needs an explicit delete
  - add support for DELETE on `/exec/<service>/<id>`, so the UI can explicitly signal that the editor is not needed anymore
  - additionally add a policy (as part of the `tech` or as a new `policies` column)
    * `delete` policy `auto`: remove as usual (services and viewers)
    * `delete` policy `poll`: regularly poll a URI on the service that indicates if the editor can be deleted
```xml
<policy type="delete>
  <poll>
    <url>url to poll</url>
    <interval>60s</interval>
  </poll>
</policy>
```

3. use the FLAT FoLiA editor as an example

**Comment by menzowindhouwer** [comment]
Also we need to get the update, which should happen during the DELETE. 

1. PUT exec/FLAT/123
2. GET exec/FLAT/123 (poll loop)
3. DELETE exec/FLAT/123 (result is copied from the service to the shared workdir)

NOTE: the deployment engine never deletes the shared workdir. That's up to the caller. DELETE, just means the current run is ended (and a subsequent GET call will return 404).

**Comment by vicding-mi** [comment]
turns out that it is related with ALLOWED_HOSTS settings of FLAT (NOT Lamachine)
After added `ALLOWED_HOSTS = ['localhost', '127.0.0.1', "latest", "lamachine"]` to file  `flat_settings.py`, public upload works!
